version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-app-prod:latest  # Explicitly setting the image name and tag
    container_name: react-app-prod
    ports:
      - '3000:3000'
    volumes:
      - ./data:/app/data
    restart: always
